force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <description>Car Details</description>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Available_For_rent__c.field-meta.xml
<CustomField>
    <fullName>Available_For_rent__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Available For rent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Build_Year__c.field-meta.xml
<CustomField>
    <fullName>Build_Year__c</fullName>
    <label>Build Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/CarType__c.field-meta.xml
<CustomField>
    <fullName>CarType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CarType</label>
    <referenceTo>CarType__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CarType__c/CarType__c.object-meta.xml
<CustomObject>
    <label>CarType</label>
    <nameField>
        <label>CarType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/carDetailsSOAPService.cls
global class carDetailsSOAPService{
    
    global class carDetailsWrapper{
        webservice String Name;
        webservice String CarType;
        webservice Boolean AvailableForRent;
        webservice Integer BuildYear;
        webservice String Contact;
        webservice String Description;
        webservice String CarId;
        
    }
    webservice static carDetailsWrapper addCarDetails(carDetailsWrapper carDetails){
        Car__c car = new Car__c();
       
        car.Name = carDetails.Name;
        car.CarType__c = carDetails.CarType;
        car.Available_For_rent__c = carDetails.AvailableForRent;
        car.Build_Year__c = carDetails.BuildYear;
        car.Contact__c = carDetails.Contact;
        car.Description__c = carDetails.Description;
       
        insert car;
        carDetails.CarId = car.Id;
        return carDetails;
      
    }
}