force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <description>Car Details</description>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Available_For_rent__c.field-meta.xml
<CustomField>
    <fullName>Available_For_rent__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Available For rent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/CarType__c.field-meta.xml
<CustomField>
    <fullName>CarType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CarType</label>
    <referenceTo>CarType__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CarType__c/CarType__c.object-meta.xml
<CustomObject>
    <label>CarType</label>
    <nameField>
        <label>CarType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/carSearchController.cls
public with sharing class carSearchController {
    @AuraEnabled
    public static List<Car__c> getCars(String carTypeId){
        //To test rollback
        //If all type selected in UI
        if(carTypeId == null && carTypeId.equalsIgnoreCase('')){
           /* return [SELECT id, Name, Picture__c, Contact__r.Name, Geolocation_latitude__s, Geolocation_longitude__s
                   FROM Car__c
                   WHERE Available_For_Rent__C = true]; */
              return [SELECT Id, Name, Picture__c, Contact__r.Name
                   FROM Car__c
                   WHERE Available_For_Rent__C = true];
        } else {
           /* return [SELECT id, Name, Picture__c, Contact__r.Name, Geolocation_latitude__s, Geolocation_longitude__s
                   FROM Car__c
                   WHERE Car_Type__c = :carTypeId
                   AND Available_For_Rent__C = true];   */
            
            		List<Car__c> carData = [SELECT Id, Name, Picture__c, Contact__r.Name
                   FROM Car__c
                   WHERE CarType__c = :carTypeId
                   AND Available_For_Rent__C = true];
                   
                 /*  return [SELECT id, Name, Picture__c, Contact__r.Name
                   FROM Car__c
                   WHERE CarType__c = :carTypeId
                   AND Available_For_Rent__C = true];*/
                        
            System.debug('Apex Car Type id' + carData);
            return carData;

        }
    }

}