force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <description>Car Details</description>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/CarType__c.field-meta.xml
<CustomField>
    <fullName>CarType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CarType</label>
    <referenceTo>CarType__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CarType__c/CarType__c.object-meta.xml
<CustomObject>
    <label>CarType</label>
    <nameField>
        <label>CarType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/carType.cls
@RestResource(urlMapping='/v1/carTypes/')
global class carType {
    @httpGet
    global static Car__c getCarType() {
        String carId;
        Car__c car = new Car__c();
        Map<String,String> mapParams = RestContext.request.params;
        carId = mapParams.get('Id');
        car = [Select Id,Name from Car__c where Id =: carId];
        return car;
    }
    @httpPost
    global static CarType__c createCarType(carTypeInfo carTypeInformation){
      
        CarType__c carType = carTypeInformation.carTypeInfo;
        insert carType;
        return carType;
    }
    
    global class carTypeInfo{
        @TestVisible CarType__c carTypeInfo {get; set;}
    }

}