force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <description>Car Details</description>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/CarType__c.field-meta.xml
<CustomField>
    <fullName>CarType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CarType</label>
    <referenceTo>CarType__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CarType__c/CarType__c.object-meta.xml
<CustomObject>
    <label>CarType</label>
    <nameField>
        <label>CarType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/carSearchController_Test.cls
@isTest
public class carSearchController_Test {

	static testMethod void insertCar()
    {
        // 20200714 comment added
        Contact objContact = new Contact();
        objContact.LastName = 'Popular';
        insert objContact;
        
        CarType__c objCarType = new CarType__c();
        objCarType.Name = 'Sedan';
        Insert objCarType;
        
        Car__c objCar = new Car__c();
        objCar.Name = 'Maruti';
        objCar.Contact__c = objContact.Id;
        objCar.CarType__c = objCarType.Id;
        insert objCar;
        
        carSearchController.getCars(objCarType.Id);
        carTypeSearch.getCarTypes(); 
  
        
        
    }
        

}